### ISSUE TITLE
Semantic version schema

### ISSUE THREAD

**Issue by dennismetz** [rrrapha/translate_locallang#87]
Not an issue, rather a question.
Could we switch to semantic versioning?

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.html#use-semantic-versions
or
https://semver.org/

It's quite confusing when you do updates and wonder why the 3.1.0 to 3.1.1 update doesn't run until you see that it's not compatible.
Here it would be better to switch to 4.0.0 or at least 3.2.0. 

Otherwise, thanks for the extension! I really like using it!

**Comment by rrrapha** [comment]
Hi @dennismetz 
Thanks for your input, you may be right with your suggestion, I'm not sure ..
Anyway, here is reason why I tagged the latest version 3.1.1:

If you're on TYPO3 v13, the changes from 3.1.0 to 3.1.1 are only bugfixes.

If you're on TYPO3 v12, composer should prevent you from getting version 3.1.1, but maybe it doesn't?

**Comment by dennismetz** [comment]
Hi @rrrapha, 
I absolutely understand the idea, but unfortunately composer always shows you that there is an update for the current version - but this only applies to v13.
And since the update only applies to v13 and v12 is not supported, it would count as breaking for v12.

![image](https://github.com/user-attachments/assets/ea35d6bf-3bc2-4a23-9d75-d53302bd385c)

**Comment by rrrapha** [comment]
Ok, thank you for this information!

**Comment by Mabahe** [comment]
Hi @dennismetz, 

I commented here https://github.com/rrrapha/translate_locallang/commit/82c797a6bc2a4e23b1e5308c6dc99c19c812de4e#r149080478
about the same topic, because I hadn't seen this issue.

> If you're on TYPO3 v13, the changes from 3.1.0 to 3.1.1 are only bugfixes.
> If you're on TYPO3 v12, composer should prevent you from getting version 3.1.1, but maybe it doesn't?

@rrrapha
You have to see the versioning in connection with the complete livecycle of the related product.
Version 12 is still supported, and here your change is a breaking change. This means that the version that introduces the breaking change has to be new MAJOR version.
Two more examples. If a bug is fixed in an extension, it is usually also fixed for the older versions. And in your case you would need version 3.1.1 for the 12 branch and 4.0.1 for the 13 branch. As it is now, you can't release a fix for the 12 branch.

Or a new feature, originally released in a 4.2.0, which should also be backported into the 12 branch, would then be a 3.2.0. This is how the core and actually all other extensions do it. 

Hope it's clearer for you now. Here is the link to the general concept of Semantic Versioning https://semver.org/
